### ISSUE TITLE
TODO List for initial release

### ISSUE THREAD

**Issue by PEMapModder** [LegendOfMCPE/xEcon#1]
- [x] Data saving (using folder database)
  - [x] Save data according to the economic entity type absolute prefix + entity absolute name
  - [x] Save data in accounts
    - [ ] Auto-tidy inventory money (insane math!)
  - [X] Logging transactions in an SQLite3 database
    - [x] Excel account exporting [feature(d)]
  - [x] Commands
    - [x] `/setcash`
      - [x] alias `/set$`
    - [x] `/addcash`
      - [x] alias `/give$`
    - [x] `/rmcash`
      - [x] alias `/rm$`
    - [x] `/setbank`
    - [x] `/addbank`
    - [x] `/rmbank`
    - [x] `/xEcon:rawadd <entity type> <entity name> <account> <amount>`
    - [x] `/xEcon:rawrm <entity type> <entity name> <account> <amount>` (maybe same superclass with `/rawadd`?)
    - [x] `/pay <player>`
    - [x] `/seemoney [account=cash] [entity name=command sender] [entity type=Player]`
  - [x] Allow third-party plugins to register economic entity types
  - [ ] By-products (ref: #2). **_Let the player choose whether to enable them._**
  - [x] Allow third-party plugins to modify data
- [x] Miscellaneous
  - [ ] Debugging! (ref: #8)
  - [ ] Grammar fixes!
  - [ ] Multi-language support! (Schedule for Beta v2.0 release of PocketMine-MP?)
- [ ] External API
  - [ ] Event system
  - [ ] Convenient getters
